[[post]]
category = "AI"
title = "AI and the Internet of Things (IoT): Creating a Connected World"
subtitle = "The Future of AI and IoT Integration"
datetime = "2023-11-09"
image = "https://media.licdn.com/dms/image/D5612AQFLbx4_f0VMSQ/article-cover_image-shrink_720_1280/0/1693219307667?e=2147483647&v=beta&t=IWFHMT8AqnO-2kecmuYHpJakAzojodwrdZfT-gqZzBE"
url = "https://aianalystbynataraj.blogspot.com/2023/11/ai-and-internet-of-things-iot-creating.html"

[[post]]
category = "version control system"
title = "Mastering Git Commands"
subtitle = "A Beginner's Guide to Essential Commands"
datetime = "2024-03-28"
image = "https://media.licdn.com/dms/image/D4D12AQFMqmbxwIiXbg/article-cover_image-shrink_720_1280/0/1704773923924?e=2147483647&v=beta&t=nTRiM081ic2_lDDS3Mr3xMB4qS_LWlvdMP4DJCWVXKo"
url = "https://www.linkedin.com/pulse/mastering-git-beginners-guide-essential-commands-nataraj-muralidharan-5iezc?utm_source=share&utm_medium=guest_desktop&utm_campaign=copy"

[[post]]
category = "App development"
title = "Low-Code App Development!"
subtitle = "Unleashing Creativity with Low-Code App Development! 🚀"
datetime = "2024-03-28"
image = "https://bigdataanalyticsnews.com/wp-content/uploads/2020/07/low-code-paltforms.png"
url = "https://www.linkedin.com/pulse/unleashing-creativity-low-code-app-development-nataraj-muralidharan-ewh8c/?trackingId=EGANNk6g%2FAs%2BHRdRbkte8w%3D%3D"

[[post]]
category = "AI"
title = "Self-Driving Cars"
subtitle = "The Future of Self-Driving Cars AI at the Wheel"
datetime = "2023-10-09"
image = "https://dda.ndus.edu/ddreview/wp-content/uploads/sites/18/2021/10/selfDriving.png"
url = "https://aianalystbynataraj.blogspot.com/2023/11/the-future-of-self-driving-cars-ai-at.html"

[[post]]
category = "AI"
title = "AI in Agriculture"
subtitle = "Feeding the Future with Technology"
datetime = "2023-10-09"
image = "https://media.licdn.com/dms/image/D4E12AQErQ0JWKpaU3g/article-cover_image-shrink_720_1280/0/1702932289325?e=2147483647&v=beta&t=JybxSi7zGcHofXrIiM77LISrjJFMZr3vLe_nzD-B98A"
url = "https://aianalystbynataraj.blogspot.com/2023/11/ai-in-agriculture-feeding-future-with.html"

[[post]]
category = "NLP"
title = "Sentiment Analysis"
subtitle = "Unveiling the Power of Sentiment Analysis: Exploring Its Diverse Use Cases 📊"
datetime = "2024-04-14"
image = "https://user-images.githubusercontent.com/81156510/180811822-1476b05d-d389-4065-9a9d-26e366aa9f68.jpg"
url = "https://aianalystbynataraj.blogspot.com/2024/04/unveiling-power-of-sentiment-analysis.html"
