[[project]]
title = "Face Recognition Attendance System"
category = "Python Scripting"
image = "https://images.expertmarket.co.uk/wp-content/uploads/2020/02/facial-recognition-attendance-system.jpg"
url = "https://github.com/leocoderz/Face-Recognition-Attendance-System"

[[project]]
title = "An Android Application To Search Nearby Business Using Kotlin"
category = "Mobile development"
image = "https://www.webstep.in/wp-content/uploads/2022/08/kotlin_app.png"
url = "https://github.com/leocoderz/AndroidMaps?tab=readme-ov-file"

[[project]]
title = "Object Detection And Recognition Using Python"
category = "Python Scripting"
image = "https://miro.medium.com/v2/resize:fit:1358/0*OAuVCw-k7XZOekBa"
url = "https://github.com/leocoderz/Object-Detection"

[[project]]
title = "Employee Attendance Dashboard"
category = "Web development"
image = "https://cdn.boldbi.com/wp/pages/dashboards/hr/hr-recruitment-thumbnail-v1.webp"
url = "https://leocoderz.github.io/html-dashboard/"

[[project]]
title = "Animated product Cart Design"
category = "Web design"
image = "https://i.ytimg.com/vi/-IIGJgQQYtM/maxresdefault.jpg"
url = "https://leocoderz.github.io/car-cart/"

[[project]]
title = "CSS Animation Dancing Robot"
category = "Web design"
image = "https://shots.codepen.io/username/pen/bZQvRQ-800.jpg?version=1553194961"
url = "https://leocoderz.github.io/dancing-robot/"

[[project]]
title = "Workout Counter"
category = "Web development"
image = "https://miro.medium.com/v2/resize:fit:1400/1*pnF_yUqNZT5mIUnPj9k56A.png"
url = "https://github.com/leocoderz/exercisecounter?tab=readme-ov-file"

[[project]]
title = "E-Commerce-Website-Using-Django"
category = "Web development"
image = "https://img.freepik.com/premium-vector/ecommerce-project-banner-landing-page-template-website_541075-1532.jpg"
url = "https://github.com/natarajnord/E-Commerce-Website-Using-Django"

[[project]]
title = "pothole-detection-using-YOLO-v8"
category = "Applications"
image = "https://viso.ai/wp-content/uploads/2023/05/pothole-detection-infrastructure-assessment-deeplearning-image-segmentation-yolov8.jpg"
url = "https://github.com/leocoderz/pothole-detection-using-YOLO-v8-task"


[[project]]
title = "Code Generation Assistant"
category = "Applications"
image = "https://assets-global.website-files.com/632cd328ed2b4829e0c3f69f/64d484cb1d6a5e3d4b6e1c2f_AI-Code-Assistant.webp"
url = "https://github.com/leocoderz/codegen-app-"

[[project]]
title = "User Registration Form "
category = "Web design"
image = "https://onaircode.com/wp-content/uploads/2017/11/Material-Design-Log-in-Sign-up.jpg"
url = "https://leocoderz.github.io/registeration-form/"

